# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  java11:
    docker:
      - image: cimg/openjdk:11.0

anchors:
  - &common_job_config
    executor: java11


jobs:
  test:
    <<: *common_job_config
    steps:
      # TODO: need to merge with destination branch before building
      - checkout
      - run:
          name: maven test
          command: mvn test

  publish-snapshot:
    <<: *common_job_config
    steps:
      - checkout
      - run:
          name: Publish -SNAPSHOT
          command: mvn -s .circleci/settings.xml -DskipTests nexus-staging -Dsnapshot=false --stacktrace

  publish-release:
    <<: *common_job_config
    steps:
      - checkout
      - run:
          name: Publish Release
          command: mvn -s .circleci/settings.xml -DskipTests deploy -P release -Dsnapshot=false --stacktrace


workflows_setup:
  - &context
    context:
      - maven_central_credentials
      - code_signing_credentials

  - &default_branch
      "main"

workflows:
  pull_request_workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore: *default_branch

  default_branch_workflow:
    when:
      # TODO: publish -SNAPSHOT for branches with branch name in the version
      equal: [ *default_branch, << pipeline.git.branch >> ]
    jobs:
      - test
      - publish-snapshot:
          <<: [ *context ]
          requires:
            - test


  publish_release:
    jobs:
      - publish-release:
          <<: [ *context ]
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/



