# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  # Build
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn -B clean package -DskipTests
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: unify-jdocs-{{ checksum "pom.xml" }}
      - run: mvn clean install -DskipTests
  # Test
  test:
    parallelism: 2 # parallel containers to split the tests among
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn test
      - store_test_results: # We use this timing data to optimize the future runs
          path: target/surefire-reports

  # Deploy
  deploy:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - command: echo ${MAVEN_REPO_USERNAME}
      - run: mvn -s .circleci/settings.xml -DskipTests deploy -P release


# Workflows that will schedule and execute jobs.
workflows:
  build-test-deploy:
    jobs:
      - build
#      - test:
#          requires:
#            - build
      - deploy:
          requires:
            - build
#            - test