# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  java11:
    docker:
      - image: cimg/openjdk:11.0


parameters:
  mvn-deploy-command:
    type: string
  internal_versioncommand:
    type: string
  new_version:
    default: true
    type: boolean
steps:
  - attach_workspace:
      at: .
  - restore_cache:
      key: 'maven-github-release-{{ checksum ".circleci/config.yml" }}'
  - configure-gpg
  - configure-git
  - run:
      name: >-
        Release new version to Maven Central and push new project version to
        repo
      command: >
        echo "Starting new release..."

        << parameters.internal_versioncommand >>

        MVN_VERSION=$(mvn -q -Dexec.executable="echo"
        -Dexec.args='${project.version}' --non-recursive exec:exec)

        echo "Releasing version ${MVN_VERSION}..."

        << parameters.mvn-deploy-command >>

        if [[ << parameters.new_version >> = true ]]; then
          echo "Pushing new version and tag..."
          git commit -am "released ${MVN_VERSION} [skip ci]"
          git tag -a ${MVN_VERSION} -m "Release ${MVN_VERSION}"
          ssh-agent sh -c 'ssh-add ~/.ssh/id_rsa; git push $CIRCLE_REPOSITORY_URL'
          ssh-agent sh -c 'ssh-add ~/.ssh/id_rsa; git push origin --tags'
        else
          echo "Version ${MVN_VERSION} is a SNAPSHOT, no version change or tag to commit..."
        fi

        echo "Successfully released ${MVN_VERSION}"
  - save_cache:
      paths:
        - ~/.m2
      key: 'maven-github-release-{{ checksum ".circleci/config.yml" }}'
