# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  java11:
    docker:
      - image: cimg/openjdk:11.0

pparameters:
  executor:
    type: executor
    default: maven-executor
  mvn-build-test-command:
    type: string
    default: echo "mvn-build-test-command not provided" 1>&2 && exit 1
  mvn-collect-artifacts-command:
    type: string
    default: 'echo "mvn-collect-artifacts-command not provided, proceeding without..."'
  steps:
    - checkout
    - restore_cache:
        key: 'maven-github-release-{{ checksum ".circleci/config.yml" }}'
    - run:
        name: Build and test script
        command: << parameters.mvn-build-test-command >>
    - persist_to_workspace:
        root: .
        paths:
          - .
    - run:
        name: Optional collect artifacts script
        shell: /bin/bash -eo pipefail -O globstar
        command: << parameters.mvn-collect-artifacts-command >>
    - store_artifacts:
        path: artifacts
    - store_test_results:
        path: artifacts/junit